In [1]:
import scipy.linalg as lin
import numpy as np
import numpy.linalg as lin
import cmath
import math
from dyn_models.filtering_lti import gen_rand_ortho_haar_real
import pickle

In [3]:
#generate a random gaussian vector
n = 5
x = np.random.randn(n)/np.sqrt(n)
print(f"x= {x}")
print(f"||x||^2= {np.linalg.norm(x)**2}")

#generate a random orthogonal matrix
#using the Haar measure
Q1 = gen_rand_ortho_haar_real(n)
Q2 = gen_rand_ortho_haar_real(n)
print(f"detQ1= {lin.det(Q1)}, detQ2= {lin.det(Q2)}")

print(f"||Q1x||^2= {np.linalg.norm(Q1@x)**2}, ||Q2x||^2= {np.linalg.norm(Q2@x)**2}")



x= [-0.37058639 -0.05326589  0.56100286  0.11749573 -0.68797822]
||x||^2= 0.9420150143771565
detQ1= 0.9999999999999997, detQ2= 1.0000000000000007
||Q1x||^2= 0.9420150143771563, ||Q2x||^2= 0.9420150143771567


In [4]:
def gen_sync_powers(sync_ind, context, Q):
    powers = np.empty((context, *Q.shape), dtype=Q.dtype)
    for i in range(context):
        p = i - sync_ind
        if p < 0:
            mat = Q.T
        else:
            mat = Q
        powers[i] = lin.matrix_power(mat, abs(p))
    return powers

def gen_sync_trace(powers, x):
    return powers @ x

In [9]:
sync_ind = 3
context = 5

x = np.random.randn(n)/np.sqrt(n)
pow1 = gen_sync_powers(sync_ind, context, Q1)
pow2 = gen_sync_powers(sync_ind, context, Q2)

x1 = gen_sync_trace(pow1, x)
x2 = gen_sync_trace(pow2, x)
print(f"x1= {x1}")
print(f"x2= {x2}")

x1= [[-0.3325998   0.1562718   0.41675527  0.27837199  0.12665283]
 [-0.47510888  0.13337606 -0.2970987  -0.25580908 -0.07097054]
 [ 0.09376479 -0.12590858 -0.23351846 -0.02776836  0.5677267 ]
 [ 0.22761422 -0.46923838  0.01608305 -0.30379759 -0.19420564]
 [ 0.52157263  0.24983321 -0.00391523  0.19659934 -0.17070174]]
x2= [[-0.36143192  0.09272912  0.05476874 -0.40579781  0.30879954]
 [ 0.26705264 -0.38380711 -0.0941311   0.38661857  0.15906217]
 [-0.48311767  0.30548741  0.10665376  0.12075279 -0.22266311]
 [ 0.22761422 -0.46923838  0.01608305 -0.30379759 -0.19420564]
 [-0.13571921  0.23735148  0.36691592  0.08188819  0.43147649]]


In [8]:
with open("/data/shared/ICL_Kalman_Experiments/train_and_test_data/ortho_haar/val_ortho_haar_ident_C_state_dim_5.pkl", "rb") as f:
    val = pickle.load(f)

In [12]:
print(type(val))
print(len(val))
print(len(val[0]["obs"]))
# print(val[0].keys())

<class 'list'>
100000
251


In [15]:
print(f"val= {val[0]["obs"].shape}")

val= (251, 5)
